### PR TITLE
Translation and German Language added.

### PR DESCRIPTION
**Pull request by acmgit**
Hello Ulla,

i've added the translation for your mod and the german translation.
But check your mod, some textures can't be found.

Greetings, Clyde.

### CODE REVIEW

**Comment by IIIullaIII** [comment]
Hi thanks for the translation,sorry for inconvenience
I updated now  the mod to the latest version with fixes etc ..
  however to be implemented.
I strongly recommend that you update the version you downloaded with the new one
And don't forget to rename the folder to "cannabis"
Greetings IIIullaIII

**Comment by acmgit** [comment]
Have you seen, i added a mod.conf in your repository.
With MT 5.x or higher and this file, where the name, the dependence and and optional dependencies are written, is the exact name of the directory not needed anymore.
Same with the translation, in MT 5.x it translates the mod, if the language is there, with 4.x, it's doing nothing and the names are english.

Greetings, Clyde.

**Comment by IIIullaIII** [comment]
Hi yes I saw it I was going to do it but thanks for doing it for me :-), I apologize again because I gave you a wrong link
in fact the correct one was cannabis 0.3, although I updated this to allow you to take advantage of it, for future changes, and updates, I'll pass the exact and definitive link of the mod, as I intend to remove the old repositories, as they only create confusion, I also updated on the forum and added the mod on contentDB in the approval phase :-P
the official repository from today on will be: [https://github.com/IIIullaIII/cannabis.git](url)

**Comment by IIIullaIII** [comment]
How is your server name? I tryed join in ("new silicon" is right?) but shutdown in and not restart

**Comment by acmgit** [comment]
Hello UIla,

the adress of Silicon Village Reload is: deadsoft.org:49152
and of Zeitsprung is: minetest.deadsoft.org:32768

Yes, you're right, the Silicon Village was down, a little bug in default, which was fixed by an update, has crashed the server, should now run ;-).

Thank you for the Info, i will now download your Mod, but for the first, i test it on the offline environments of my server ;-).

Greetings, Clyde.

**Comment by IIIullaIII** [comment]
Ok thanks, of course you must always test it out of the server, I do it with all the mods, even the most famous or well-known ones, as in some cases they may be incompatible with others, which maybe I prefer: -P, I also have small minds in mind improvements, which I will upload with an update but first I have to finish doing them (I started yesterday) and test them :-) if you have any problems with the mod I would be grateful if you let me know, thanks
Regards

**Comment by acmgit** [comment]
I have reworked your Mod a little, you should have a PR ;-).

**Pull request merged**
