### PR TITLE
Reworked and new translated in German.

### PR DESCRIPTION
**Pull request by acmgit**
Hello Ulla,

i reworked your mod a little bit, because there were some troubles:

The second directory named cannabis has prevented MT to load the mod after a git clone.
If you use more than mod in a directory, you have to create a modpack, but in this case, it was not neccdessary to create a modpack. It's a single Mod.

I new added the translations to your mod. If you want to update it, you have to run the added python-script i18n.py and after them, you have to edit your translation-files.

Take a look at your joint.lua, i added the translation-strings there, but the problem is, they are in italy. Better is, you change them to english and translate it to italy, then i can translate it to german.

I added the italian translation, but you have to complete it, because my italy is to few to translate all in a correct shape ;-).

Before you merge, create a new branch and pull it then, so you can see and test all the changes i made.

Hope you like it and greetings,
Clyde.

P.S.:
Only a comment, is it necessary to add the admin-tools?
They nice and the idea behind is good, but i think, an admin installs an own admin-mod which provides such tools.
IMHO is it dangerous to provide to much admin-stuff as mods, better this tools are in an own mod.

### CODE REVIEW

**Comment by IIIullaIII** [comment]
1)

> The second directory named cannabis has prevented MT to load the mod after a git clone.

Is normal i know
in this regard I created a new repository that I sent you in a previous message, and that will be the one to use :-p that is this: [https://github.com/IIIullaIII/cannabis.git](url)
because the folder must be the name of the mod

> I new added the translations to your mod. If you want to update it, you have to run the added python-script i18n.py and after them, you have to edit your translation-files.

Thanks a lot i will add the translations

> Take a look at your joint.lua, i added the translation-strings there, but the problem is, they are in italy. Better is, you change them to english and translate it to italy, then i can translate it to german.

You're right I learned it some time ago and yesterday I was just thinking about doing it and today I will do it :-P

> Only a comment, is it necessary to add the admin-tools?
They nice and the idea behind is good, but i think, an admin installs an own admin-mod which provides such tools.
IMHO is it dangerous to provide to much admin-stuff as mods, better this tools are in an own mod.

If you mean admin armor and admin sword and admin block
1) The armor from admin, in reality it is only very powerful, against the pvp the lava etc .... But it is damaged anyway, for example it does not protect from the effects of the corium technic chernobilite etc .... it does not protect all infinite from the lava, but allows to be able to cross it for a while. In reality the name is misleading and attractive and was born not for the admin, but as a very powerful armor (there should also be the craft that I have disabled, I have to check), it takes a long time to craft it in fact the idea was that, if someone had the patience to craft it, let's say he deserved it :-)
2) The admin block is only an unbreackable block like those of maptools, useful for signaling and creating rooms for administrators, example with commandblock inside etc ... it is also craftable but always with a long time, so as to make the desire go away , to create enough to make a 2x1 base :-P
3) The real danger, for this not craftable, is the sword that actually works by removing and killing everything, without returning anything similar to admin pickaxe, this perhaps would be better to weaken it, excluding the removal force of the unbreakable blocks and make it craftable (always with a long time), initially I did not want it to drop, to use it in constructions to throw directly without spamming with blocks on the ground, but in reality as a garbage can, therefore shaped like a sword and not a pickaxe.
Maybe what I should do is rename them not to confuse the admin? So far I have not considered it necessary
as "adminh" is not exactly "admin" but to make players want to have them :-P
I accept advice: XD
 now I look at what you've done and change what I have to
thanks again
Regards

**Comment by IIIullaIII** [comment]
Hello I finished now :-P I noticed that there were some errors that I had previously fixed ,but that I probably had not saved, and they were on a harddisk that I lost :-( , however, it should be in place now, there were also too many scripts in tools , I still have to improve and implement it.
thanks for the help, I’ll wait for your translation then I’ll update it.
Greetings

**Comment by acmgit** [comment]
> > The second directory named cannabis has prevented MT to load the mod after a git clone.
> 
> Is normal i know

Except you insert a file with the name modpack.txt.
Then MT will accept it as a collection of mods.

> in this regard I created a new repository that I sent you in a previous message, and that will be the one to use :-p that is this: [https://github.com/IIIullaIII/cannabis.git](url)
Yes, i've seen it ;-).

> because the folder must be the name of the mod 
No, since 5.x not anymore.
This is the reason, why you should create or use since 5.x the mod.conf file.
This should have:
name=name of the mod
dependence=the dependencies of the mod
optional_dependence=the optional dependence
If you have such file in at your mod added, the name of the directory doesn't matter.

> > I new added the translations to your mod. If you want to update it, you have to run the added python-script i18n.py and after them, you have to edit your translation-files.
> 
> Thanks a lot i will add the translations
>
The new translation of 5.x works really well ;-).
 
> > Only a comment, is it necessary to add the admin-tools?
> > They nice and the idea behind is good, but i think, an admin installs an own admin-mod which provides such tools.
> > IMHO is it dangerous to provide to much admin-stuff as mods, better this tools are in an own mod.
> 
> If you mean admin armor and admin sword and admin block
> 
>     1. The armor from admin, in reality it is only very powerful, against the pvp the lava etc .... But it is damaged anyway, for example it does not protect from the effects of the corium technic chernobilite etc .... it does not protect all infinite from the lava, but allows to be able to cross it for a while. In reality the name is misleading and attractive and was born not for the admin, but as a very powerful armor (there should also be the craft that I have disabled, I have to check), it takes a long time to craft it in fact the idea was that, if someone had the patience to craft it, let's say he deserved it :-)
> 
>     2. The admin block is only an unbreackable block like those of maptools, useful for signaling and creating rooms for administrators, example with commandblock inside etc ... it is also craftable but always with a long time, so as to make the desire go away , to create enough to make a 2x1 base :-P
> 
>     3. The real danger, for this not craftable, is the sword that actually works by removing and killing everything, without returning anything similar to admin pickaxe, this perhaps would be better to weaken it, excluding the removal force of the unbreakable blocks and make it craftable (always with a long time), initially I did not want it to drop, to use it in constructions to throw directly without spamming with blocks on the ground, but in reality as a garbage can, therefore shaped like a sword and not a pickaxe.
>        Maybe what I should do is rename them not to confuse the admin? So far I have not considered it necessary
>        as "adminh" is not exactly "admin" but to make players want to have them :-P

Yes, admin sounds like super-power-stuff ;-).
And the pickaxe?

>        I accept advice: XD
>         now I look at what you've done and change what I have to
>        thanks again
>        Regards

You're welcome, if you have reworked your translation strings, i will translate it then into german ;-).

Greetings, Clyde.

**Comment by IIIullaIII** [comment]
> Except you insert a file with the name modpack.txt.
Then MT will accept it as a collection of mods.

Yes I had glimpsed it a short time ago but I had not yet educated enough, I have to update myself :-P

> Yes, admin sounds like super-power-stuff ;-).
And the pickaxe?
As I was saying before, maybe it’s the only dangerous thing and maybe it doesn’t make sense to exist like this, I have to weaken it
I didn’t even remember the existence of another admin pickaxe only obtainable in chatcommand that I have now removed :-P

> You're welcome, if you have reworked your translation strings, i will translate it then into german ;-).

yes 

Greetings ulla

**Comment by IIIullaIII** [comment]
So, according to what we’ve been saying, I’m removing the other repositories and leaving this?

**Comment by IIIullaIII** [comment]
hello as I have modified some functions and also some textures I have updated and added the translations directly to the master you can also remove this branch and add the German translations that are now missing
greetings ulla

**Comment by IIIullaIII** [comment]
hi add alot of change and traslate too german can you see if right traduction?
ty 
adde hemp ice and bag for unifed inventory  in onor of Real Bad Angel added cloth and reworked texture  fixed biome spawn plant but i need work a bit more for biome ,but I would wait because I saw that in 5.2 they changed something to the papyrus biome and as the green hemp works similarly and depends on default I would not want to do anything for the v7 works well for the v6 works too low a bit the values
greetings ulla

**Pull request merged**
